### ISSUE TITLE
Are there plans for a java18 org.codehaus.mojo.signature artifact?

### ISSUE THREAD

**Issue by krismcqueen** [mojohaus/animal-sniffer#1]
My project is in the process of setting the baseline Java version to 1.8.  We use the animal-sniffer plugin to ensure API compatibility and I was not able to find a java18 org.codehaus.mojo.signature artifact on maven central.  I had a couple of questions:

- Am I looking in the wrong place for the java18 signature artifact?  Has the groupId changed from org.codehaus.mojo.signature?
- Are there plans for a java18 signature that we will should make use of going forward? (note: animal sniffer checks can be disabled in our builds or we can generate a java18 signature for use locally, but we'd use the officially blessed java18 signature from maven central if available)

Thanks.  Very useful plugin.

**Comment by rombert** [comment]
+1, we need this as well in the Apache Sling project ( see [SLING-4702|https://issues.apache.org/jira/browse/SLING-4702] ).

**Comment by amitm78** [comment]
+1 we have a similar requirement as well.

**Comment by rinokadijk** [comment]
+1

**Comment by trevmex** [comment]
+1, we have disabled animal-sniffer on our Java 8 projects, and would love to have it back.

**Comment by sharathsrinivasa** [comment]
+1

**Comment by giacgbj** [comment]
+1

**Comment by JaXt0r** [comment]
+1

**Comment by praste** [comment]
Can't we generate one on your own using instructions on 
http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/examples/generating-java-signatures.html 

Of course it won't be available in maven central but for those how have internal repo in your organization that can a good interim solution.

**Comment by user667** [comment]
+1

**Comment by burtsevyg** [comment]
+1

**Comment by baev** [comment]
+1

**Comment by rfscholte** [comment]
It has just been released.

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>animal-sniffer-maven-plugin</artifactId>
        <configuration>
          <signature>
            <groupId>org.codehaus.mojo.signature</groupId>
            <artifactId>java18</artifactId>
            <version>1.0</version>
          </signature>
        </configuration>
      </plugin>

**Comment by nobeh** [comment]
Is it still on its way to Maven Central? Still the last one listed is 1.14. Thanks!

**Comment by giacgbj** [comment]
@nobeh, 1.14 is the version of animal-sniffer-maven-plugin, while this thread is about the [signature for Java 8](http://search.maven.org/#artifactdetails%7Corg.codehaus.mojo.signature%7Cjava18%7C1.0%7Cpom).

**Comment by nobeh** [comment]
Right, indeed, I mixed the two for a moment.

**Comment by lukehutch** [comment]
Related question: How will the signatures for Java 11 etc. be named? In future there will need to be a hyphen or something inserted, to disambiguate `java17` for Java 1.7 from say `java-17` for Java 17.

**Comment by olamy** [comment]
@lukehutch I think this project is dead now :) starting with java 9 you can simply use the option `-release` and that's it :) 
read http://openjdk.java.net/jeps/247
```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
            <release>9</release>
          </configuration>
        </plugin>
```

**Comment by lukehutch** [comment]
@olamy: ah, I wondered why there hadn't been any updates. Makes a lot of sense. Thanks for the explanation!
