### ISSUE TITLE
[bug] provided wrong url in your web page.

### ISSUE THREAD

**Issue by XenoAmess** [mojohaus/animal-sniffer#100]
see http://www.mojohaus.org/animal-sniffer/animal-sniffer/source-repository.html

```
Web Access
The following is a link to the online source repository.
https://github.com/mojohaus/animal-sniffer/animal-sniffer
```

should be:

```
Web Access
The following is a link to the online source repository.
https://github.com/mojohaus/animal-sniffer
```

**Comment by slawekjaranowski** [comment]
Current page: https://www.mojohaus.org/animal-sniffer/animal-sniffer/scm.html

**Comment by slawekjaranowski** [comment]
to check in pom `scm/url` and examine output of `mvn site site:stage` in `target/stage`
