### ISSUE TITLE
Undefined reference: java.util.concurrent.ConcurrentHashMap.KeySetView java.util.concurrent.ConcurrentHashMap.keySet()

### ISSUE THREAD

**Issue by sleicht** [mojohaus/animal-sniffer#12]
Followup to #8: 
With the project https://github.com/aclemons/animal-sniffer-npe and usage of 1.15-SNAPSHOT the NPE is solved but a new issue comes up: `animal-sniffer-npe/src/main/java/nz/caffe/sniffer/NullPointerAnimalSniffer.java:30: Undefined reference: java.util.concurrent.ConcurrentHashMap.KeySetView java.util.concurrent.ConcurrentHashMap.keySet()`

This isn't true and the signature error doesn't get raised if mvn is started with jre 1.7 but if mvn is started with jre 1.8 the check doesn't work correct.

**Comment by aclemons** [comment]
Actually the return type of ConcurrentHashMap.keySet() changed between JDK7 and JDK8 so I would say the plugin is doing what is expected here. If you compile this code with JDK8 but expect to run it on JDK7, it will fail at runtime.

**Comment by sleicht** [comment]
but the linked project has set the compiler-plugin to 1.7:

```
      <plugin>
        <inherited>true</inherited>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
          <optimize>false</optimize>
          <debug>true</debug>
        </configuration>
      </plugin>
```

**Comment by aclemons** [comment]
Yes the bytecode generated is for 1.7 but it doesn't change what the JDK is providing (here with JDK8 a different return type - subclass of Set)

So yes, the project is supposed to fail. The plugin saves you here from having this code fail at runtime. I ran across the origin NPE because I had some code like this. The fix is simple: `final ConcurrentMap<String, String> values = new ConcurrentHashMap<>();`

**Comment by sleicht** [comment]
Now I see, thanks for the clarification. And one should either way only declare a variable with the interface and not the implementation.
