### ISSUE TITLE
Push back to github the animal-sniffer jdk signatures

### ISSUE THREAD

**Issue by tchemit** [mojohaus/animal-sniffer#16]
I can't find any repository containing the signatures of jdk API, was it migrate from CodeHaus ?

According for example to https://repo1.maven.org/maven2/org/codehaus/mojo/signature/java17/1.0/java17-1.0.pom

I will make this work, I'd like to create then the jdk 1.8 signatures. (#1)

**Comment by olamy** [comment]
no idea maybe @kohsuke  or @stephenc  ?

**Comment by stephenc** [comment]
seems the signatures were not migrated @hboutemy @rfscholte @batmat anyone know what happened?

**Comment by rfscholte** [comment]
I wasn't part of the migration, but these signatures are kind of special since there are no sources, just a pom file. A tag might give the idea that a re-run would give the same result, but that's not true (it depends on your jre installation on your system). For that reason I've decided to release the java18 signature without SCM.
We still need the docs though, the links to signatures still gives a 404.

**Comment by stephenc** [comment]
I think the tags and source are important to have even if less useful

**Comment by batmat** [comment]
Note that I created a Docker image to twiddle with the original SVN repository, usable by anyone having Docker available. 

See https://github.com/mojohaus/convert-to-git/blob/master/README.md#subversion---git-conversion
   
It's supposed to make the conversion process simple and declarative:
```
docker run --rm -v $PWD/newrepo:/newgitrepo \
           -e projectName=aspectj-maven-plugin \
           -e trunkPath=trunk/mojo/aspectj-maven-plugin \
           -e tagsStartsWith=aspectj-maven-plugin- \
           -e branches="" \
       batmat/mojohaus-converter
```

Would be really interesting if someone else than me can actually verify that that works. If need be, I can also do that conversion myselft. We just need to agree on what to use: which URL(s), and so on.

**Comment by batmat** [comment]
And for reference, the full list of the migrated repositories should be here: https://github.com/mojohaus/convert-to-git/blob/master/repo-infos.csv

Not everything was migrated: I didn't want to spend hours to find the right paths for each mojo, so I asked other committers to enrich the file above to that end.

**Comment by olamy** [comment]
I think we can close that.
