### ISSUE TITLE
False-positives on @PolymorphicSignature methods

### ISSUE THREAD

**Issue by sewe** [mojohaus/animal-sniffer#18]
When compiled, calls to `MethodHandle.invoke` and `MethodHandle.invokeExact` produce `invokevirtual`s with non-existing signatures (see the [compilation section in `MethodHandle` Javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/MethodHandle.html)). This causes false positives, i.e., animal-sniffer complains about an “undefined reference” even though the call is legal.

**Comment by i386** [comment]
@sewe did you find a workaround for this?

**Comment by i386** [comment]
@olamy do you know the right way to fix this? Any pointers would be great.

**Comment by sewe** [comment]
> @sewe did you find a workaround for this?

@i386 No, I don’t have a workaround, except from the wholesale [exclusion of problematic dependencies](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/check-mojo.html#excludeDependencies).

> @olamy do you know the right way to fix this? Any pointers would be great.

AFAIK, [`animal-sniffer:build`](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/build-mojo.html) creates a file with all known signatures. As a `@PolymorphicSignature` method can essentially have any signature, it should be listed in that file, but marked as a special wildcard case. The checking logic would then need to take this wildcard marker into account.

**Comment by i386** [comment]
@sewe ahh right on. Ive ended up adding it to `ignores` for now.

**Comment by mikroskeem** [comment]
Any updates on this?
