### ISSUE TITLE
Execution java18-sniff-test of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.22:check failed: PermittedSubclasses requires ASM9

### ISSUE THREAD

**Issue by wilx** [mojohaus/animal-sniffer#230]
We are getting the following failure:
```
Execution java18-sniff-test of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.22:check failed: PermittedSubclasses requires ASM9
```
It seems to me that this should be fixed by replacing several uses of `Opcodes.ASM7` with `Opcodes.ASM9` in the animal sniffer code. But I am not familiar with the ASM library, so I do not know if this has any additional consequence.

**Comment by slachiewicz** [comment]
thx for suggestion - I've updated code to use Opcodes.ASM9 in f343158c4af67cb1af514fdba862a30edf4e27b4

**Comment by slawekjaranowski** [comment]
Version 1.23 released
