### ISSUE TITLE
Are there plans to release animal-sniffer `1.24`?

### ISSUE THREAD

**Issue by armandino** [mojohaus/animal-sniffer#268]
The latest animal-sniffer version `1.23` has a dependency on [ASM 9.4](https://asm.ow2.io/versions.html) which does not support Java 21. As a result, animal-sniffer fails if it encounters Java 21 classes.

Currently, the workaround is to specify the latest ASM dependency for the plugin:

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>animal-sniffer-maven-plugin</artifactId>
    <version>1.23</version>
    <dependencies>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>9.6</version>
        </dependency>
    </dependencies>
    ...
</plugin>
```

I noticed the `master` branch already depends on the latest ASM version. It would be great if it was published as a new release to add support for Java 21.

**Comment by slachiewicz** [comment]
Released
