### ISSUE TITLE
Allow users to invoke animal-sniffer from the Maven command line

### ISSUE THREAD

**Issue by gabrielsjoberg** [mojohaus/animal-sniffer#3]
People who manage large code-bases or build systems sometimes do not have direct access to the underlying POMs.  One way of adding important checks such as API compatibility is to invoke the tools directly from the command line, with the configuration specified at the same time.

Animal-sniffer doesn't currently allow users to specify the API signature on the command line, which means it cannot be run without modifications to the POM.

I've filed PR #2 to add the appropriate Mojo goodness.

**Comment by olamy** [comment]
fixed thanks for the pull request!!
