### ISSUE TITLE
Dead link in usage page

### ISSUE THREAD

**Issue by lukaseder** [mojohaus/animal-sniffer#46]
The usage page http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/usage.html contains a dead link labelled: "Animal Scents subproject", linking to http://mojo.codehaus.org/signatures

**Comment by stefanbirkner** [comment]
It looks like signatures-parent was once an own subproject (https://web.archive.org/web/20150316102617/http://mojo.codehaus.org:80/signatures/source-repository.html) Unfortunately it is not part of mojohaus anymore. @mojohaus/owners Does anybody know what happened to the project?

**Comment by hbeni** [comment]
I think i found the new link target: https://mvnrepository.com/artifact/org.codehaus.mojo.signature

**Comment by wilx** [comment]
+1

**Comment by slawekjaranowski** [comment]
Correct link is: https://www.mojohaus.org/signatures/

PR are welcome
