### ISSUE TITLE
java 1.8 as minimum

### ISSUE THREAD

**Issue by olamy** [mojohaus/animal-sniffer#55]
because we are in mid 2018 so it's time to get rid of java 1.7 support :)

**Comment by davewichers** [comment]
What does 'fixed' mean? In my testing it appears that starting with v1.18 Java 8 is required for this plugin, but I can't find any reference to the Java version required in the documentation. When I look here: https://www.mojohaus.org/animal-sniffer/index.html and here: https://www.mojohaus.org/animal-sniffer/animal-sniffer/index.html I see no minimum Java version specified. I also notice the 2nd page refers to v1.16 while the 1st page says v1.19 so the later page should be deleted or updated.

Can you update the documentation to make it super clear which versions of Java are required for the various versions? And we are using this plugin to verify Java 7 compatibility for a library so this 'broke' our usage and we have to stick with v1.17 I guess.
