### ISSUE TITLE
Java 11 signature

### ISSUE THREAD

**Issue by 40rn05lyv** [mojohaus/animal-sniffer#62]
Hi, currently I use the animal-sniffer Maven plugin with Java 8 signature using following dependency https://mvnrepository.com/artifact/org.codehaus.mojo.signature/java18
We have plans to migrate to Java 11, but I can't find an existing signature for it (and also I didn't find Java 9 and 10 signatures too).
Will be very grateful for your answers.

**Comment by khmarbaise** [comment]
Starting with JDK9+ you can't define a full API signature cause based on the module system you can define your own (limited view on JDK). Apart from that you can use the release configuration in maven-compiler-plugin with JDK9+ to have exactly what animal sniffer offers and that's the reason why there are no JDK9+ signatures.

**Comment by rfscholte** [comment]
The javac tool has been extended with the `release` flag in Java 9, which does the signature checking like animal-sniffer. So there's no reason to create signatures for Java 9 and beyond.
See https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9__GUID-D343F6B4-3FDD-43A8-AD24-43DD70214471 and https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release
