### ISSUE TITLE
java.lang.UnsupportedOperationException: This feature requires ASM7

### ISSUE THREAD

**Issue by pburka** [mojohaus/animal-sniffer#76]
When I try to run animal-sniffer on a library compiled with Java 11, I get the following error:
```
java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:243)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:669)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker.process(SignatureChecker.java:197)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:174)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:120)
```

It looks like animal-sniffer was recently updated to depend on asm 7.0, but internally it still uses `ASM5`. This should be a simple matter of replacing `ASM5` with `ASM7` in `SignatureChecker.java`, to indicate to asm that newer constructs, such as nests, may be reported (even if animal-sniffer simply ignores them).

**Comment by olamy** [comment]
TBH If you are using Java 11 simply look at the flag `release`

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <source>${compiler.source}</source>
            <target>${compiler.target}</target>
            <release>${compiler.release}</release>
          </configuration>
        </plugin>
```

**Comment by rfscholte** [comment]
There's absolutely no requirement for animal sniffer anymore since Java 9. You should use the release-flag (which support was actually inspired by animal sniffer)

**Comment by pburka** [comment]
The release-flag only works for JDK libraries. We're using animal sniffer to check projects against other projects. I think there are still applications for animal sniffer in Java 9 and beyond.

**Comment by Plexcalibur** [comment]
We also moved to Java11, but still depend on animal-sniffer to automatically check projects against other projects while deploying them dynamically in the same jvm.
This project is really great and we are really really happy with the safety layer it provides for our continous delivery.
So we really need to have the issue from the original poster fixed, because we also ran into it.

**Comment by Finomosec** [comment]
**I got Animal-Sniffer to work with Java 11.**

_**Steps:**_

1. Patch `SignatureChecker.java` to use `ASM7` instead of `ASM5` in 2 places.
2. Upgrade ASM library to 7+
3. Use the following code to create the signature for the currently active JRE:

```
private byte[] createJRESignature(Logger log) throws Exception {
  ByteArrayOutputStream signatureStream = new ByteArrayOutputStream();
  MySignatureBuilder signatureBuilder = new SignatureBuilder(signatureStream, log);
  Files.walkFileTree(Paths.get(URI.create("jrt:/modules")), Collections.emptySet(), 1000, new SimpleFileVisitor<Path>() {

    @Override
    public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
      log.info("Creating JRT signatures for: " + dir);
      return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
      if (file.getFileName().toString().endsWith(".class")) {
        try {
          signatureBuilder.setCheckJars(false);
          signatureBuilder.process(file);
        } catch (Throwable t) {
          log.error("Error creating API signature for: " + file, t);
        }
      }
      return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult visitFileFailed(Path file, IOException exc) throws IOException {
      return FileVisitResult.CONTINUE;
    }

  });
  signatureBuilder.close();
  return signatureStream.toByteArray();
}

// usage:
SignatureChecker checker = new SignatureChecker(new ByteArrayInputStream(createJRESignature(log)), ignoredPackages, log);
```

**Comment by olamy** [comment]
@Finomosec maybe you can provide a PR?

**Comment by szpak** [comment]
I hit the same today. @Finomosec will you be able to provide a PR for that?

**Comment by Finomosec** [comment]
> I hit the same today. @Finomosec will you be able to provide a PR for that?

here you go:
https://github.com/mojohaus/animal-sniffer/pull/91

**Comment by Wazii414** [comment]
* ### Google Admob Unity Plugin v7.3.1 or **Higher**

**### Unity Solution**

- Delete the folder that is in Library\Bee\**Android** <= **Delete this folder**
- Full path => Main_Project_Folder\Library\Bee\**Android** <= **Delete this folder**


* I have tried this and my issue is resolved.
* Thank You !!!
