### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by steven-sheehy** [mojohaus/animal-sniffer#85]
Missing a checked in LICENSE file. This file is needed to comply with license compliance when being used as a transitive dependency.

**Comment by robcos** [comment]
The link is broken and it points to a generic MIT license.
Can you please fix it / confirm that MIT is the right license? Otherwise we (the world!) may not be able to use this code anymore
https://www.mojohaus.org/animal-sniffer/animal-sniffer-annotations/license.html

**Comment by olamy** [comment]
the pom is clear on this topic https://github.com/mojohaus/animal-sniffer/blob/master/pom.xml

**Comment by steven-sheehy** [comment]
Hi @olamy, thanks for the response. The pom includes an embedded license header and also fills out the license section of the pom, which is good. But having a standalone LICENSE file is necessary for use in some cloud providers.

In our case, Google runs our application for customers as a service on our behalf in Google Cloud Marketplace and we have to fill out a [open source compliance worksheet](https://cloud.google.com/marketplace/docs/partners/open-source-compliance). To meet those requirements we have to download and include the full license in the container image as well as provide a link to the full license on the project's actual website. The first part is met by the pom but it's not clear if it's acceptable to Google provide a link to a source file that happens to include a license header.

Since it is standard practice to include a LICENSE file in the project root and it will help us meet the cloud provider's requirement, I would suggest one be added. GitHub also has special handling around such a file that's nice to have. I will submit a PR to do so.

**Comment by robcos** [comment]
Same for my company!
