### ISSUE TITLE
animal-sniffer don't include the license file

### ISSUE THREAD

**Issue by puntogil** [mojohaus/animal-sniffer#9]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by puntogil** [comment]
Hi
Found one files have "unknown" license.
animal-sniffer-animal-sniffer-parent-1.14/animal-sniffer-ant-tasks/src/main/java/org/codehaus/mojo/animal_sniffer/ant/Annotation.java
Please, add license header in the above file
Thanks in advance
Regards

**Comment by olamy** [comment]
@kohsuke  as you are the original author maybe something you can do?

**Comment by olamy** [comment]
fixed
